package com.asuis.qudesign.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.asuis.qudesign.db.model.ScheduleItem;
import com.asuis.qudesign.db.model.User;

import com.asuis.qudesign.db.model.ScheduleItemDao;
import com.asuis.qudesign.db.model.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scheduleItemDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ScheduleItemDao scheduleItemDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scheduleItemDaoConfig = daoConfigMap.get(ScheduleItemDao.class).clone();
        scheduleItemDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        scheduleItemDao = new ScheduleItemDao(scheduleItemDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ScheduleItem.class, scheduleItemDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        scheduleItemDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ScheduleItemDao getScheduleItemDao() {
        return scheduleItemDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
