package com.asuis.qudesign.db.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCHEDULE_ITEM".
*/
public class ScheduleItemDao extends AbstractDao<ScheduleItem, Void> {

    public static final String TABLENAME = "SCHEDULE_ITEM";

    /**
     * Properties of entity ScheduleItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Time = new Property(0, String.class, "time", false, "TIME");
        public final static Property Desc = new Property(1, String.class, "desc", false, "DESC");
    }


    public ScheduleItemDao(DaoConfig config) {
        super(config);
    }
    
    public ScheduleItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCHEDULE_ITEM\" (" + //
                "\"TIME\" TEXT," + // 0: time
                "\"DESC\" TEXT);"); // 1: desc
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCHEDULE_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ScheduleItem entity) {
        stmt.clearBindings();
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(1, time);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(2, desc);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ScheduleItem entity) {
        stmt.clearBindings();
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(1, time);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(2, desc);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ScheduleItem readEntity(Cursor cursor, int offset) {
        ScheduleItem entity = new ScheduleItem( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // time
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // desc
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ScheduleItem entity, int offset) {
        entity.setTime(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDesc(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ScheduleItem entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ScheduleItem entity) {
        return null;
    }

    @Override
    public boolean hasKey(ScheduleItem entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
